{
 "title": "CDN Comparison - Performance Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "countryCode", "label": "Country", "query": "US,ES,DE,IN,RU,IE,SE,SG,TR" },
   { "name": "percentile", "query": "10,50,75,90,95,99" }
  ]
 },
 "panels": [
  { "title": "Aggregated", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cache Hit Ratio (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as chr by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,cdn,chr",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    },
    {
     "expression": "fields concat(event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\"\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as Global by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,Global,'-',cdn",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate",
   "type": "stat",
   "description": "gzip/br compression rate",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats avg(event_details.compRate) as compression by metadata.countryCode,bin(5m) as event_timestamp\n|display event_timestamp,metadata.countryCode,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "metadata.countryCode",
      "event_timestamp"
     ]
    },
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" \n|stats avg(event_details.compRate) as overall by 'overall',bin(5m) as event_timestamp\n|display event_timestamp,overall",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  {
   "title": "${countryCode}:PageViews",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"com.amazon.rum.performance_navigation_event\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats count(*) as pageviews by metadata.deviceType as device \n|display device,pageviews",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "device" ]
    }
   ]
  },
  {
   "title": "Total Page Views",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expression": "filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats count(*) as ${countryCode} by event_details.cdn,bin(5m)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "event_details.cdn",
      "bin(5m)"
     ]
    },
    {
     "expression": "filter event_type=\"com.amazon.rum.performance_navigation_event\" \n|stats count(*) as Global by 'overall',bin(5m)",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default"
    }
   ]
  },
  { "title": "Pages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cache Hit Ratio (avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as chr by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,cdn,chr",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats avg(event_details.compRate) as compression by cdn,bin(5m) as event_timestamp\n|display event_timestamp,cdn,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page: TLS connect time (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.tlstime,${percentile}) as tlstime by cdn,bin(1m) as event_timestamp\n| display event_timestamp,cdn,tlstime\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page: Load time (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.pageload,${percentile}) as pageload by cdn,bin(1m) as event_timestamp\n| display event_timestamp, cdn, pageload\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page: Time to First Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttfb,${percentile}) as ttfb by cdn,bin(1m) as event_timestamp\n| display event_timestamp, cdn, ttfb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Page: Time to Last Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"navigation\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttlb,${percentile}) as ttlb by cdn,bin(1m) as event_timestamp\n| display event_timestamp, cdn, ttlb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "Images", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cache Hit Ratio (avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"img\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as chr by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,cdn,chr",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Images: TLS connect time (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"img\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.tlstime,${percentile}) as tlstime by cdn ,bin(1m) as event_timestamp\n| display event_timestamp, cdn, tlstime\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Images: Time to First Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"img\" and metadata.countryCode in [${countryCode:singlequote}]\n| pct(event_details.ttfb,${percentile}) as ttfb by cdn ,bin(1m) as event_timestamp\n| display event_timestamp, cdn, ttfb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Images: Time to Last Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"img\" and metadata.countryCode in [${countryCode:singlequote}]\n| pct(event_details.ttlb,${percentile}) as ttlb by cdn ,bin(1m) as event_timestamp\n| display event_timestamp, cdn, ttlb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "Scripts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cache Hit Ratio (avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"script\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as chr by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,cdn,chr",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"script\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats avg(event_details.compRate) as compression by cdn,bin(5m) as event_timestamp\n|display event_timestamp,cdn,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Scripts: TLS connect time (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"script\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.tlstime,${percentile}) as tlstime by cdn ,bin(1m) as event_timestamp\n| display event_timestamp,cdn,tlstime\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Scripts: Time to First Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"script\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttfb,${percentile}) as ttfb by cdn,bin(1m) as event_timestamp\n| display event_timestamp,cdn,ttfb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Scripts: Time to Last Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n| filter event_type=\"cdn_metrics\" and event_details.type=\"script\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttlb,${percentile}) as ttlb by cdn,bin(1m) as event_timestamp\n| display event_timestamp,cdn,ttlb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  { "title": "CSS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Cache Hit Ratio (avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"link\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats sum(event_details.cachestatus=\"MISS\") as cachemiss,sum(event_details.cachestatus=\"HIT\") as cachehit,cachehit/(cachemiss+cachehit) as chr by cdn,bin(5m) as event_timestamp\n|display  event_timestamp,cdn,chr",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "Compression Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"link\" and metadata.countryCode in [${countryCode:singlequote}]\n|stats avg(event_details.compRate) as compression by cdn,bin(5m) as event_timestamp\n|display event_timestamp,cdn,compression",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "CSS: TLS connect time (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"link\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.tlstime,${percentile}) as tlstime by cdn ,bin(1m) as event_timestamp\n| display event_timestamp,cdn,tlstime\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "CSS: Time to First Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"link\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttfb,${percentile}) as ttfb by cdn ,bin(1m) as event_timestamp\n| display event_timestamp,cdn,ttfb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  },
  {
   "title": "CSS: Time to Last Byte (p${percentile})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expression": "fields concat(metadata.countryCode,'-',event_details.cdn) as cdn\n|filter event_type=\"cdn_metrics\" and event_details.type=\"link\" and metadata.countryCode in [${countryCode:singlequote}]\n| stats pct(event_details.ttlb,${percentile}) as ttlb by cdn ,bin(1m) as event_timestamp\n| display event_timestamp,cdn,ttlb\n",
     "logGroupNames": [
      "/aws/vendedlogs/RUMService_us-east-1-cdncwrumstackv194bd5b43"
     ],
     "queryMode": "Logs",
     "region": "us-east-1",
     "statsGroups": [
      "cdn",
      "event_timestamp"
     ]
    }
   ]
  }
 ]
}